---
- name: Install Packages for Docker-Compose
  become: true
  apt:
    pkg:
    - docker-compose

- name: Add user Will to the docker and plugdev group
  become: true
  user:
    name: will
    groups: docker,plugdev
    append: true
