---
- name: Update and upgrade apt packages
  become: true
  apt:
    autoremove: true
    upgrade: 'full'
    update_cache: true
    cache_valid_time: 86400  # One day

- name: Install Packages for all
  become: true
  apt:
    pkg:
    - ack
    - bash-completion
    - git
    - htop
    - lm-sensors
    - nfs-common
    - openssh-server
    - tree
    - ufw
    - vim
    - yadm
    - yamllint
