---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400  # One day

- name: Install Packages for all
  become: true
  apt:
    pkg:
    - git
    - hddtemp
    - htop
    - lm-sensors
    - nfs-common
    - openssh-server
    - vim
    - yadm
    - yamllint
