---
- name: Allow port 8000 for pihole webGUI
  become: true
  ufw:
    rule: allow
    port: '8000'
    proto: any

- name: Allow port 53 for DNS
  become: true
  ufw:
    rule: allow
    port: '53'
    proto: any
