---
- name: Allow port 51412 for torrent traffic
  become: true
  ufw:
    rule: allow
    port: '51412'
    proto: any

- name: Allow port 9091 for transmission webGUI and torrents
  become: true
  ufw:
    rule: allow
    port: '9091'
    proto: tcp
