---
- name: Allow port 51412 for torrent traffic
  become: true
  ufw:
    rule: allow
    port: 51412
    proto: any

- name: Allow port 30100 for transmission webGUI and torrents
  become: true
  ufw:
    rule: allow
    port: 30100:30101
    proto: tcp
    delete: true
