---
- hosts: storage
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/create_will.yml
    - import_tasks: tasks/nginx.yml
    - import_tasks: tasks/docker-compose.yml

    - name: Install Packages for Barstorage
      become: true
      apt:
        pkg:
        - ansible
        - unrar
        - tailscale
        - zfsutils-linux
