---
- hosts: k3cluster
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/create_will.yml
    - import_tasks: tasks/k3s.yml
    - import_tasks: tasks/nginx.yml
    - import_tasks: tasks/pihole.yml
    - import_tasks: tasks/transmission.yml
    - import_tasks: tasks/unifi.yml

    - name: Create cert dir
      file:
        path: /home/will/certs
        state: directory
        mode: 0755
        group: will
        owner: will

    - name: SudoBot nginx private key
      copy:
        src: ../../files/sudobot/STAR_sudoservers_com.key
        dest: /home/will/certs/STAR_sudoservers_com.key
        owner: will
        group: will
        mode: 0644

    - name: SudoBot nginx cert
      copy:
        src: ../../files/sudobot/STAR_sudoservers_com.crt
        dest: /home/will/certs/STAR_sudoservers_com.crt
        owner: will
        group: will
        mode: 0644
