---
- hosts: k3cluster
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/system.yml
    - import_tasks: tasks/create_will.yml
    - import_tasks: tasks/k3s.yml
    - import_tasks: tasks/nginx.yml
    - import_tasks: tasks/transmission.yml
    - import_tasks: tasks/unifi.yml
